[package]
name = "blaze_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
# TCP Dependencies
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

# Configuration dependencies
serde = { version = "1", features = ["derive"] }
toml = "0.8"